name: league_music_player
description: "Frontend for League Music Player"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.9.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.10.0
  audioplayers: ^6.5.1
  flutter_chips_input: ^2.0.0
  chips_choice: ^3.0.1
  url_launcher: ^6.2.0
  fluent_ui: ^4.0.0
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.0
  system_theme: ^2.0.0
  bitsdojo_window: ^0.1.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/certs/cacert.pem
    - assets/genres.txt